
<div id="productinfo">
    <div id="viewerImage">
            <?php echo $this->getFoto($this->product['id'],2); ?>
    </div>
    <div id="viewerInfo">
            <h1 class="title-product">
                <span>
                    <?php echo $this->escape(($this->product['titel'])); ?>
                </span>
            </h1>

            <h2 class="teaser-product">
                <span>
                    <?php echo $this->escape(($this->product['teaser'])); ?>
                </span>
            </h2>

            <div class="prod-desc">
                    <?php echo $this->escape(($this->product['inhoud'])); ?>
            </div>

            <div class="prod-cat">
                <?php
                    if (!empty($this->categorie)) {
                        foreach($this->categorie as $c) {
                            echo "<p>".$this->escape($c['label'])."</p>";
                        }
                    }
                ?>
            </div>
            <?php echo $this->ToonProductstatus($this->product['status']); ?>

            

            <div class="prod-price">
                <?php echo $this->ShowCurrency($this->product['eenheidsprijs']); ?>
            </div>
        
            <form action="" method="post" enctype="multipart/form-data">
            <div class="add_to_cart_button">
                <a href="#"><div class="add_to_cart_image_button">In de winkelwagen</div></a>
            </div>
            <div class="qty-price">
                <label>Aantal</label>
                <?php
                $elemAttribs = array('class' => 'onlyDecimals', 'name' => 'Aantal' , 'style' => 'width:40px; font-size:22px;');
                echo $this->formText('Aantal',1,$elemAttribs);
                echo $this->formHidden('id',$this->product['id']); 
                ?>
            </div>
            </form>
        
            <div class="prod-foto">
            <?php
            if (!empty($this->fotos)) {
                foreach($this->fotos as $f) {
            ?>
                <img class="productimage-3" src="<?php echo "/".$this->escape($f['filePath']).$this->escape($f['fileName']); ?>">
                <?php
               }
            }
            ?>
            </div>
</div>
    <?php //echo $this->form; ?>

<div class="divLoading"></div>
<?php echo $this->render('/index/_jsCustom_productinfo.phtml'); ?>