<section id="paginainfo">
    <h2 class="title-pagina"><?php echo $this->pagina['titel']; ?></h2>
    <section>
        <h3 class="teaser-pagina"><?php echo $this->pagina['teaser']; ?></h3>
    <article>
        <h4 class="hidden">Dit is de inhoud van de pagina</h4>
            <div class="pagina-desc">
                <?php echo $this->escape(trim($this->pagina['inhoud'])); ?>
            </div>
    </article>
    </section>
</section>
