<!doctype>
<?php
header('Content-Type: text/html; charset=utf-8');
echo '<?xml version="1.0" encoding="UTF-8" ?>'.PHP_EOL;
echo $this->doctype().PHP_EOL; ?>
<html>    
    <head>
        <title>Eindwerk SyntraWest - Webmaster-Advanced 2013 - Webshop Thomas Vanhuysse</title>
        <link href="/css/style.css" rel="stylesheet" />
        <?php
            echo $this->jQuery().PHP_EOL;
            echo $this->headScript();
        ?>
    </head>
    
    <body>
        
        <section id="container">
            <aside>
                <h1 class="hidden">Dit is de linkermarge van de webpagina</h1>
                <section class="logo">
                 <figure>
                        <img src="/images/logo.png" alt="Logo">
                        <figcaption>Logo</figcaption>
                 </figure>
                </section>
                <br/>
                <section class="firma">
                    <h3 class="hidden">Firmagegevens</h3>
                    <?php echo $this->ShowFirm($_SESSION['context']['firma']); ?>
                </section>                
            </aside>

            <header>
                 <h1 class="hidden">Webhop Eindwerk SyntraWest Webmaster Advanced</h1>
                 <section class="lang">
                 <h3 class="hidden">Taalkeuze</h3>
                       <?php echo $this->toonLocale(); ?>
                 </section>

                 <nav>
                    <h2 class="hidden">Dit is de navigatie van de website</h2>
                    <?php
                    $partial = array('menu.phtml', 'default');
                    $this->navigation()->menu()->setPartial($partial);
                    ?>                    
                    <?php echo $this->navigation()->menu()->addPageClassToLi(true); ?>
                    <br />
                </nav>

                
                <section class="winkelmand">
                    <?php
                            if (isset($_SESSION['context']['winkelmand'])){
                                echo $this->ToonWinkelmand($_SESSION['context']['winkelmand']);
                            }
                            else {
                                echo $this->ToonWinkelmand(null);
                            }
                    ?>
                </section>

                
                <section class="login">
                 <h3 class="hidden">Loginformulier</h3>
                       <?php echo $this->signupForm($this->signupForm); ?>
                </section>

                <section class="search">
                 <h3 class="hidden">Zoekformulier</h3>
                       <?php echo $this->searchForm($this->searchForm); ?>
                </section>
            </header>

            <section id="content">
                <h1 class="hidden">De content...</h1>
                <section id="mainTitle">
                <h1 class="hidden">Error messages</h1>
                       <?php echo $this->placeholder('mainTitle') ?>
                </section>
                <?php echo $this->layout()->content; ?>
            </section>

            <footer>
                <h1 class="hidden">De footer...</h1>
                 <?php echo $this->ShowFirm($_SESSION['context']['firma']);?>
            </footer>

        </section>
    </body>
</html>


