<!doctype>
<?php
header('Content-Type: text/html; charset=utf-8');
echo '<?xml version="1.0" encoding="UTF-8" ?>'.PHP_EOL;
echo $this->doctype().PHP_EOL; ?>
<html>    
    <head>
        <title>Eindwerk SyntraWest - Webmaster Advanced - Webwinkel - Thomas Vanhuysse</title>
        <link href="/css/style.css" rel="stylesheet" />
        <?php
            echo $this->jQuery().PHP_EOL;
            echo $this->headScript();
        ?>
    </head>
    
    <body>
        
        <div id="container">
            <aside>
                <h1 class="hidden">Dit is de linkermarge van de webpagina</h1>
                <section class="logo">
                 <figure>
                        <img src="/images/logo.jpg" width="100" alt="Logo">
                        <figcaption></figcaption>
                 </figure>
                </section>
                <br/>
                <section class="firma">
                    <?php
                        if (isset($_SESSION['context']['Firma'])) {
                            echo $this->ShowFirm($_SESSION['context']['Firma']);
                        }
                    ?>
                </section>
                <section class="winkelmand">
                    <?php
                        if (isset($_SESSION['context']['winkelmand'])) {
                            echo $this->ToonWinkelmand($_SESSION['context']['winkelmand']);
                        } else {
                            echo $this->ToonWinkelmand(null);
                        }
                    ?>
                </section>
            </aside>

            <header>
                 <h1 class="hidden">Webhop Eindwerk SyntraWest Webmaster Advanced</h1>
                 <nav>
                    <h2 class="hidden">Dit is de navigatie van de website</h2>
                    <?php
                    $partial = array('menu.phtml', 'default');
                    $this->navigation()->menu()->setPartial($partial);
                    ?>                    
                    <?php echo $this->navigation()->menu()->addPageClassToLi(true); ?>
                    <br />
                </nav>
                            <section id="lang">
                            <h3 class="hidden">Taalkeuze</h3>
                            <?php echo $this->toonLocale(); ?>
                            </section>
                            <section class="login">
                            <h3 class="hidden">Loginformulier</h3>
                                <?php echo $this->signupForm($this->signupForm); ?>
                            </section>
             </header>
            <section id="content">
                <h1 class="hidden">De content...</h1>
                <section id="mainTitle">
                <h1 class="hidden">Berichten pagina</h1>
                                <?php echo $this->placeholder('mainTitle') ?>
                </section>
                <?php echo $this->layout()->content; ?>
            </section>    
        </div>
    </body>
</html>


